import { SceneId, VariantSelection } from "../content/types";
import { createSceneSimulationEngine } from "./sceneSimulation";
import { AnimationState, EncounterBeat, InteractionPolicy, SceneDefinition, SceneScore, SimulationPreferences } from "./types";

export const defaultVariantSelection: VariantSelection = { figureGround: "natural", motion: "intermittent", sound: "off", novelty: "familiar" };

const frame = { minX: .045, maxX: .955, minY: .065, maxY: .935 } as const;
type RawSceneScore = Omit<SceneScore, "encounter" | "interactionPolicy">;
const authoredSceneScores: Readonly<Record<SceneId, RawSceneScore>> = {
  "balcony-birds": { id: "balcony-birds", durationMs: 105_000, actorCount: [1, 2], baseSpeed: .078, maxSpeed: .31, maxAcceleration: .76, displayWidth: .2, containment: frame, subjectHitRadius: .14, authoredStates: ["perching", "hopping", "flying", "reappearing"], touchPolicy: { refractoryMs: 5_000, allowedResponses: ["reroute", "pause"] }, audioEventKinds: ["ordinary-call", "wing"], behaviors: [{ state: "perching", durationMs: [5_000, 9_500], poseFrames: [0, 1, 0, 2], trajectory: "perch" }, { state: "hopping", durationMs: [700, 1_100], poseFrames: [3], trajectory: "perch" }, { state: "flying", durationMs: [1_500, 2_800], poseFrames: [4, 5, 6, 5], trajectory: "spline" }, { state: "reappearing", durationMs: [700, 1_200], poseFrames: [4, 5, 6, 5], trajectory: "spline" }], trajectoryRule: "Rail-aligned perch points joined by short eased arcs; flight exits re-enter behind the nearest rail or planter.", occlusionZones: [{ id: "rail", minX: 0, maxX: 1, minY: .68, maxY: 1 }, { id: "planter", minX: .04, maxX: .31, minY: .62, maxY: .9 }], audioEventMappings: { "ordinary-call": "perching", wing: "flying" }, lowMotionOverride: { actorCount: 1, travelScale: .28, deformationScale: 0, maxSimultaneousEvents: 1 } },
  "koi-pool": { id: "koi-pool", durationMs: 120_000, actorCount: [1, 3], baseSpeed: .032, maxSpeed: .1, maxAcceleration: .2, displayWidth: .18, containment: frame, subjectHitRadius: .13, authoredStates: ["swimming", "gliding", "reappearing"], touchPolicy: { refractoryMs: 4_500, allowedResponses: ["redirect"] }, audioEventKinds: ["quiet-water"], behaviors: [{ state: "gliding", durationMs: [4_200, 7_500], poseFrames: [5], trajectory: "spline" }, { state: "swimming", durationMs: [5_500, 9_500], poseFrames: [5, 1, 5, 7], trajectory: "spline" }, { state: "reappearing", durationMs: [900, 1_600], poseFrames: [5, 1, 5, 7], trajectory: "spline" }], trajectoryRule: "Independent broad arcs with gradual tangent changes; short propulsive bouts alternate with straight-body coasts.", occlusionZones: [{ id: "plant-shadow", minX: .55, maxX: .96, minY: .68, maxY: .94 }], audioEventMappings: { "quiet-water": "swimming" }, lowMotionOverride: { actorCount: 1, travelScale: .32, deformationScale: .18, maxSimultaneousEvents: 1 } },
  "paper-moth": { id: "paper-moth", durationMs: 90_000, actorCount: [1, 1], baseSpeed: .09, maxSpeed: .24, maxAcceleration: .64, displayWidth: .16, containment: frame, subjectHitRadius: .13, authoredStates: ["fluttering", "landed", "reappearing"], touchPolicy: { refractoryMs: 4_000, allowedResponses: ["reroute", "land"] }, audioEventKinds: ["paper-flutter"], behaviors: [{ state: "fluttering", durationMs: [1_800, 3_800], poseFrames: [0, 1, 2, 3, 2, 1], trajectory: "flutter" }, { state: "landed", durationMs: [5_000, 10_000], poseFrames: [0], trajectory: "perch" }, { state: "reappearing", durationMs: [800, 1_400], poseFrames: [0, 1, 2, 3, 2, 1], trajectory: "flutter" }], trajectoryRule: "Short heading-persistent passages terminate at the window or frame; re-entry begins near the last disappearance.", occlusionZones: [{ id: "window-frame", minX: .86, maxX: 1, minY: 0, maxY: 1 }, { id: "lamp-edge", minX: 0, maxX: .08, minY: 0, maxY: 1 }], audioEventMappings: { "paper-flutter": "fluttering" }, lowMotionOverride: { actorCount: 1, travelScale: .25, deformationScale: .15, maxSimultaneousEvents: 1 } },
  "beetle-under-the-fern": { id: "beetle-under-the-fern", durationMs: 95_000, actorCount: [1, 1], baseSpeed: .042, maxSpeed: .105, maxAcceleration: .3, displayWidth: .14, containment: frame, subjectHitRadius: .11, authoredStates: ["crawling", "sheltering", "reappearing"], touchPolicy: { refractoryMs: 4_000, allowedResponses: ["pause", "reverse", "hide"] }, audioEventKinds: ["leaf-scratch"], behaviors: [{ state: "crawling", durationMs: [5_000, 9_500], poseFrames: [0, 1, 2, 3], trajectory: "ground" }, { state: "sheltering", durationMs: [3_000, 6_500], poseFrames: [7], trajectory: "ground" }, { state: "reappearing", durationMs: [900, 1_500], poseFrames: [0, 1, 2, 3], trajectory: "ground" }], trajectoryRule: "Low ground-plane segments follow fern margins with antenna pauses and reversible headings.", occlusionZones: [{ id: "left-fern", minX: 0, maxX: .3, minY: .08, maxY: .46 }, { id: "right-fern", minX: .7, maxX: 1, minY: .25, maxY: .65 }], audioEventMappings: { "leaf-scratch": "crawling" }, lowMotionOverride: { actorCount: 1, travelScale: .3, deformationScale: .2, maxSimultaneousEvents: 1 } },
  "red-string": { id: "red-string", durationMs: 100_000, actorCount: [1, 1], baseSpeed: .07, maxSpeed: .18, maxAcceleration: .55, displayWidth: .04, containment: frame, subjectHitRadius: .13, authoredStates: ["dragging", "resting", "reappearing"], touchPolicy: { refractoryMs: 3_500, allowedResponses: ["pause", "redirect"] }, audioEventKinds: ["fabric-drag"], behaviors: [{ state: "dragging", durationMs: [3_600, 6_900], poseFrames: [0, 1, 2, 4, 7], trajectory: "rope" }, { state: "resting", durationMs: [2_400, 4_600], poseFrames: [3, 5], trajectory: "rope" }, { state: "reappearing", durationMs: [600, 1_000], poseFrames: [6, 7], trajectory: "rope" }], trajectoryRule: "Spline control points alternate tensioned pulls and slack curves with bounded partial edge exits.", occlusionZones: [{ id: "left-edge", minX: 0, maxX: .055, minY: 0, maxY: 1 }, { id: "right-edge", minX: .945, maxX: 1, minY: 0, maxY: 1 }], audioEventMappings: { "fabric-drag": "dragging" }, lowMotionOverride: { actorCount: 1, travelScale: .3, deformationScale: .25, maxSimultaneousEvents: 1 } },
};
const encounterStates: Record<SceneId, readonly [AnimationState, AnimationState, AnimationState]> = {
  "balcony-birds": ["perching", "flying", "perching"], "koi-pool": ["gliding", "swimming", "gliding"], "paper-moth": ["landed", "fluttering", "landed"], "beetle-under-the-fern": ["sheltering", "crawling", "sheltering"], "red-string": ["resting", "dragging", "resting"],
};
const encounterFor = (score: RawSceneScore): readonly EncounterBeat[] => {
  const [resting, moving, finale] = encounterStates[score.id];
  const trajectory = score.behaviors.find((behavior) => behavior.state === moving)?.trajectory ?? score.behaviors[0].trajectory;
  const beat = (phase: EncounterBeat["phase"], fraction: readonly [number, number], behaviorState: AnimationState, rule: string): EncounterBeat => ({ id: `${score.id}:${phase}`, phase, durationMs: [score.durationMs * fraction[0], score.durationMs * fraction[1]], behaviorState, trajectory, occlusionRule: rule, actorCap: score.actorCount[1], eligibleAudioEvent: score.audioEventKinds[0], allowedContactResponse: score.touchPolicy.allowedResponses });
  return [beat("invitation", [.07, .09], resting, "Subject remains plainly visible."), beat("passage", [.29, .31], moving, "Movement follows the authored corridor."), beat("occlusion", [.08, .1], moving, "Use the nearest authored cover zone."), beat("reappearance", [.08, .1], "reappearing", "Return adjacent to the last cover location."), beat("contact-response", [.12, .14], moving, "A contact may alter this beat once."), beat("rest", [.17, .19], resting, "Motion settles without adding stimuli."), beat("finale", [.12, .14], finale, "Subject finishes visibly at rest.")];
};
const completeScore = (score: RawSceneScore): SceneScore => {
  const normalized = score.id === "koi-pool" ? { ...score, actorCount: [1, 1] as const } : score;
  const interactionPolicy: InteractionPolicy = { targetOnly: true, hitTolerance: normalized.subjectHitRadius, refractoryMs: normalized.touchPolicy.refractoryMs, rollingContactCap: { contacts: 3, windowMs: 20_000 }, restResponse: { durationMs: [10_000, 12_000], editorialSafetyCap: true }, neverEscalate: true };
  return { ...normalized, encounter: encounterFor(normalized), interactionPolicy };
};
export const sceneScores: Readonly<Record<SceneId, SceneScore>> = Object.fromEntries(Object.entries(authoredSceneScores).map(([id, score]) => [id, completeScore(id === "balcony-birds" ? { ...score, touchPolicy: { refractoryMs: 5_000, allowedResponses: ["head-turn", "hop"] } } : score)])) as unknown as Readonly<Record<SceneId, SceneScore>>;
export const sceneDefinitions: Readonly<Record<SceneId, SceneDefinition>> = sceneScores;

const sceneScoreMap = new Map<SceneId, SceneScore>(Object.entries(sceneScores) as [SceneId, SceneScore][]);
const sceneScoreFor = (sceneId: SceneId): SceneScore => {
  const score = sceneScoreMap.get(sceneId);
  if (!score) throw new Error(`Unknown scene: ${sceneId}`);
  return score;
};
const createSceneSimulation = (sceneId: SceneId, variants: VariantSelection = defaultVariantSelection, seed = 1, preferences: SimulationPreferences = {}) => createSceneSimulationEngine(sceneId, sceneScoreFor(sceneId), variants, seed, preferences);
const getSceneDefinition = (id: SceneId): SceneDefinition => sceneScoreFor(id);
const getSceneScore = (id: SceneId): SceneScore => sceneScoreFor(id);
export { createSceneSimulation, getSceneDefinition, getSceneScore };
