import { anything, arrayOf, fields, number, oneOf, optional, string, text } from "../validation/descriptors";

export const assetDescriptor = fields({ assetId: text(), creator: text(), source: text("/assets/"), license: text(), derivativeHistory: arrayOf(text(), 1), checksum: text(), masteringFormat: oneOf("webp", "avif", "png", "opus", "mp3", "wav"), contentRevision: text() });
export const motionDescriptor = fields({ apparentSpeed: oneOf("still", "slow", "measured", "variable"), trajectory: arrayOf(oneOf("curved", "direct", "fluttering", "grounded", "authored"), 1), intermittency: oneOf("continuous", "continuous-with-pauses", "intermittent"), directionChanges: oneOf("none", "gentle", "frequent", "authored"), entranceEdges: arrayOf(oneOf("top", "right", "bottom", "left"), 1), exitEdges: arrayOf(oneOf("top", "right", "bottom", "left"), 1), acceleration: oneOf("none", "gentle", "brief", "variable"), occlusion: fields({ frequency: oneOf("none", "occasional", "recurring"), duration: oneOf("brief", "variable", "sustained") }) });
export const apparentSizeDescriptor = fields({ frameWidthPercent: arrayOf(number(0, 100), undefined, 2), intendedViewingDistance: oneOf("near-screen", "room-display", "mixed"), visualAngle: oneOf("device-dependent"), basis: oneOf("editorial-legibility") });
export const contrastDescriptor = fields({ natural: text(), enhanced: text() });
export const visualPackageDescriptor = fields({ backgroundPlateUrl: text("/assets/"), subjectPoseSheetUrl: text("/assets/"), foregroundOcclusion: oneOf("renderer-authored"), alternateTreatment: text() });
export const encounterDescriptor = fields({ authoredScore: text(), finale: text(), presentation: fields({ tablet: fields({ distance: oneOf("near-screen"), frameWidthPercent: arrayOf(anything()) }), television: fields({ distance: oneOf("room-display"), frameWidthPercent: arrayOf(anything()) }) }), targetCorridorRationale: text(), backgroundComplexityRationale: text(), contactResponseSemantics: text(), restBehavior: text(), riskRationale: fields({ edgeExits: text(), repeatedContact: text(), occlusion: text(), audio: text() }), editorialClaims: arrayOf(fields({ claim: text(), evidenceEndpoint: text(), confidence: oneOf("limited", "moderate") }), 1) });
export const audioDescriptor = fields({ enabledVariant: oneOf("on"), ambience: optional(oneOf("water", "fabric", "leaves")), eventKinds: arrayOf(text(), 1), sourceCoherent: oneOf(true), startsMuted: oneOf(true), excluded: arrayOf(text(), 1), provenance: optional(arrayOf(fields({ eventKind: text(), source: text(), license: text(), eligible: oneOf(true, false) }))) });
export const requiredManifestTextFields = ["title", "revision", "apparentSizeGuidance", "motionProfile", "occlusion", "supervision", "evidenceEndpoint", "noveltyFamily", "posterUrl"] as const;
export const finiteDurationDescriptor = number();
